# Generated by Django 6.0.1 on 2026-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='current_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
