# Generated by Django 6.0.1 on 2026-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dockerregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
