# Generated by Django 6.0.1 on 2026-02-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tool_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DockerRegistry',
        ),
    ]
